// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#include "TarinoiGeneratedVariables.h"

#include "Tarinoi.h"

FTarinoiValue UTarinoiFixtureStateVariables::GetVariable_Implementation(FName Name)
{
	if (Name == FName(TEXT("anything")))
	{
		return Anything;
	}
	if (Name == FName(TEXT("gold")))
	{
		return FTarinoiValue::MakeNumber(Gold);
	}
	if (Name == FName(TEXT("met_ferryman")))
	{
		return FTarinoiValue::MakeBool(MetFerryman);
	}
	if (Name == FName(TEXT("mood")))
	{
		return FTarinoiValue::MakeString(Mood);
	}
	if (Name == FName(TEXT("player_name")))
	{
		return FTarinoiValue::MakeString(PlayerName);
	}
	UE_LOG(LogTarinoi, Warning, TEXT("UTarinoiFixtureStateVariables has no variable '%s'. Regenerate your bindings."), *Name.ToString());
	return FTarinoiValue();
}

void UTarinoiFixtureStateVariables::SetVariable_Implementation(FName Name, const FTarinoiValue& Value)
{
	if (Name == FName(TEXT("anything")))
	{
		Anything = Value.Resolve();
		return;
	}
	if (Name == FName(TEXT("gold")))
	{
		Gold = Value.ToNumber();
		return;
	}
	if (Name == FName(TEXT("met_ferryman")))
	{
		MetFerryman = Value.ToBool();
		return;
	}
	if (Name == FName(TEXT("mood")))
	{
		Mood = Value.ToString();
		return;
	}
	if (Name == FName(TEXT("player_name")))
	{
		PlayerName = Value.ToString();
		return;
	}
	UE_LOG(LogTarinoi, Warning, TEXT("UTarinoiFixtureStateVariables has no variable '%s'. Regenerate your bindings."), *Name.ToString());
}
