// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#include "TarinoiGeneratedFunctions.h"

bool UTarinoiFixtureGlobalFunctions::CheckGate_Implementation(const FTarinoiValue& Door)
{
	LogUnimplemented(TEXT("CheckGate"));
	return false;
}

FTarinoiValue UTarinoiFixtureGlobalFunctions::Describe_Implementation(const FTarinoiValue& Thing)
{
	LogUnimplemented(TEXT("Describe"));
	return FTarinoiValue();
}

FString UTarinoiFixtureGlobalFunctions::PickPin_Implementation()
{
	LogUnimplemented(TEXT("PickPin"));
	return FString();
}

void UTarinoiFixtureGlobalFunctions::FnRename_Implementation(const FTarinoiValue& Who)
{
	LogUnimplemented(TEXT("FnRename"));
}

double UTarinoiFixtureGlobalFunctions::Roll_Implementation(const FTarinoiValue& Sides, const FTarinoiValue& Bonus)
{
	LogUnimplemented(TEXT("Roll"));
	return 0.0;
}

bool UTarinoiFixtureGlobalFunctions::HasFunction(FName Name) const
{
	static const FName Names[] = {
		FName(TEXT("CheckGate")),
		FName(TEXT("Describe")),
		FName(TEXT("PickPin")),
		FName(TEXT("Rename")),
		FName(TEXT("Roll")),
	};
	for (const FName& Known : Names)
	{
		if (Known == Name)
		{
			return true;
		}
	}
	return false;
}

bool UTarinoiFixtureGlobalFunctions::TryInvoke(FName Name, const TArray<FTarinoiValue>& Args, FTarinoiValue& OutResult)
{
	// A plain dispatch on the authored name, calling each BlueprintNativeEvent, so a
	// Blueprint override is reached the same way as a C++ one.
	OutResult = FTarinoiValue();

	static const FName NameCheckGate(TEXT("CheckGate"));
	if (Name == NameCheckGate)
	{
		if (ArityMatches(Name, Args, 1))
		{
			OutResult = FTarinoiValue::MakeBool(CheckGate(Args[0]));
		}
		return true;
	}

	static const FName NameDescribe(TEXT("Describe"));
	if (Name == NameDescribe)
	{
		if (ArityMatches(Name, Args, 1))
		{
			OutResult = Describe(Args[0]);
		}
		return true;
	}

	static const FName NamePickPin(TEXT("PickPin"));
	if (Name == NamePickPin)
	{
		if (ArityMatches(Name, Args, 0))
		{
			OutResult = FTarinoiValue::MakeString(PickPin());
		}
		return true;
	}

	static const FName NameFnRename(TEXT("Rename"));
	if (Name == NameFnRename)
	{
		if (ArityMatches(Name, Args, 1))
		{
			FnRename(Args[0]);
		}
		return true;
	}

	static const FName NameRoll(TEXT("Roll"));
	if (Name == NameRoll)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeNumber(Roll(Args[0], Args[1]));
		}
		return true;
	}

	return false;
}

void UTarinoiFixtureTarinoiFunctions::ClearFlag_Implementation(const FTarinoiValue& FlagRef)
{
	LogUnimplemented(TEXT("ClearFlag"));
}

bool UTarinoiFixtureTarinoiFunctions::FlagIsSet_Implementation(const FTarinoiValue& FlagRef)
{
	LogUnimplemented(TEXT("FlagIsSet"));
	return false;
}

void UTarinoiFixtureTarinoiFunctions::IncrementCounter_Implementation(const FTarinoiValue& CounterRef, const FTarinoiValue& Delta)
{
	LogUnimplemented(TEXT("IncrementCounter"));
}

bool UTarinoiFixtureTarinoiFunctions::NumberAtLeast_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("NumberAtLeast"));
	return false;
}

bool UTarinoiFixtureTarinoiFunctions::NumberAtMost_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("NumberAtMost"));
	return false;
}

bool UTarinoiFixtureTarinoiFunctions::NumberEquals_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("NumberEquals"));
	return false;
}

bool UTarinoiFixtureTarinoiFunctions::NumberGreaterThan_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("NumberGreaterThan"));
	return false;
}

bool UTarinoiFixtureTarinoiFunctions::NumberLessThan_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("NumberLessThan"));
	return false;
}

void UTarinoiFixtureTarinoiFunctions::SetCounter_Implementation(const FTarinoiValue& CounterRef, const FTarinoiValue& Value)
{
	LogUnimplemented(TEXT("SetCounter"));
}

void UTarinoiFixtureTarinoiFunctions::SetFlag_Implementation(const FTarinoiValue& FlagRef)
{
	LogUnimplemented(TEXT("SetFlag"));
}

void UTarinoiFixtureTarinoiFunctions::SetText_Implementation(const FTarinoiValue& TextRef, const FTarinoiValue& Value)
{
	LogUnimplemented(TEXT("SetText"));
}

bool UTarinoiFixtureTarinoiFunctions::StringEquals_Implementation(const FTarinoiValue& A, const FTarinoiValue& B)
{
	LogUnimplemented(TEXT("StringEquals"));
	return false;
}

void UTarinoiFixtureTarinoiFunctions::ToggleFlag_Implementation(const FTarinoiValue& FlagRef)
{
	LogUnimplemented(TEXT("ToggleFlag"));
}

bool UTarinoiFixtureTarinoiFunctions::HasFunction(FName Name) const
{
	static const FName Names[] = {
		FName(TEXT("ClearFlag")),
		FName(TEXT("FlagIsSet")),
		FName(TEXT("IncrementCounter")),
		FName(TEXT("NumberAtLeast")),
		FName(TEXT("NumberAtMost")),
		FName(TEXT("NumberEquals")),
		FName(TEXT("NumberGreaterThan")),
		FName(TEXT("NumberLessThan")),
		FName(TEXT("SetCounter")),
		FName(TEXT("SetFlag")),
		FName(TEXT("SetText")),
		FName(TEXT("StringEquals")),
		FName(TEXT("ToggleFlag")),
	};
	for (const FName& Known : Names)
	{
		if (Known == Name)
		{
			return true;
		}
	}
	return false;
}

bool UTarinoiFixtureTarinoiFunctions::TryInvoke(FName Name, const TArray<FTarinoiValue>& Args, FTarinoiValue& OutResult)
{
	// A plain dispatch on the authored name, calling each BlueprintNativeEvent, so a
	// Blueprint override is reached the same way as a C++ one.
	OutResult = FTarinoiValue();

	static const FName NameClearFlag(TEXT("ClearFlag"));
	if (Name == NameClearFlag)
	{
		if (ArityMatches(Name, Args, 1))
		{
			ClearFlag(Args[0]);
		}
		return true;
	}

	static const FName NameFlagIsSet(TEXT("FlagIsSet"));
	if (Name == NameFlagIsSet)
	{
		if (ArityMatches(Name, Args, 1))
		{
			OutResult = FTarinoiValue::MakeBool(FlagIsSet(Args[0]));
		}
		return true;
	}

	static const FName NameIncrementCounter(TEXT("IncrementCounter"));
	if (Name == NameIncrementCounter)
	{
		if (ArityMatches(Name, Args, 2))
		{
			IncrementCounter(Args[0], Args[1]);
		}
		return true;
	}

	static const FName NameNumberAtLeast(TEXT("NumberAtLeast"));
	if (Name == NameNumberAtLeast)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(NumberAtLeast(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameNumberAtMost(TEXT("NumberAtMost"));
	if (Name == NameNumberAtMost)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(NumberAtMost(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameNumberEquals(TEXT("NumberEquals"));
	if (Name == NameNumberEquals)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(NumberEquals(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameNumberGreaterThan(TEXT("NumberGreaterThan"));
	if (Name == NameNumberGreaterThan)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(NumberGreaterThan(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameNumberLessThan(TEXT("NumberLessThan"));
	if (Name == NameNumberLessThan)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(NumberLessThan(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameSetCounter(TEXT("SetCounter"));
	if (Name == NameSetCounter)
	{
		if (ArityMatches(Name, Args, 2))
		{
			SetCounter(Args[0], Args[1]);
		}
		return true;
	}

	static const FName NameSetFlag(TEXT("SetFlag"));
	if (Name == NameSetFlag)
	{
		if (ArityMatches(Name, Args, 1))
		{
			SetFlag(Args[0]);
		}
		return true;
	}

	static const FName NameSetText(TEXT("SetText"));
	if (Name == NameSetText)
	{
		if (ArityMatches(Name, Args, 2))
		{
			SetText(Args[0], Args[1]);
		}
		return true;
	}

	static const FName NameStringEquals(TEXT("StringEquals"));
	if (Name == NameStringEquals)
	{
		if (ArityMatches(Name, Args, 2))
		{
			OutResult = FTarinoiValue::MakeBool(StringEquals(Args[0], Args[1]));
		}
		return true;
	}

	static const FName NameToggleFlag(TEXT("ToggleFlag"));
	if (Name == NameToggleFlag)
	{
		if (ArityMatches(Name, Args, 1))
		{
			ToggleFlag(Args[0]);
		}
		return true;
	}

	return false;
}
