// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#pragma once

#include "CoreMinimal.h"

/** Identifiers of the entities that can take part in dialogue, as Ent.collection.name names them. */
namespace TarinoiEntities
{
	/** Ent.cast.* */
	namespace Cast
	{
		constexpr const TCHAR* Ferryman = TEXT("ferryman");
		constexpr const TCHAR* Narrator = TEXT("narrator");
	}
}
