// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#pragma once

#include "CoreMinimal.h"

/** Option keys for the authored lists, as Ls.collection.list.key names them. */
namespace TarinoiLists
{
	/** Ls.global.* */
	namespace Global
	{
		namespace Thresholds
		{
			constexpr const TCHAR* Easy = TEXT("easy");
			constexpr const TCHAR* Hard = TEXT("hard");
			constexpr const TCHAR* Heroic = TEXT("heroic");
		}
	}
}
