// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#pragma once

#include "Bindings/TarinoiBindings.h"
#include "CoreMinimal.h"

#include "TarinoiFixtureGeneratedVariables.generated.h"

/**
 * State the author reads and writes as Var.state.*
 *
 * The properties hold the values: set them from game code, or derive (in C++ or Blueprint)
 * and override GetVariable/SetVariable to keep them somewhere else, such as a save game.
 */
UCLASS(Blueprintable, BlueprintType, meta = (TarinoiCollection = "state"))
class TARINOITESTS_API UTarinoiFixtureStateVariables : public UTarinoiVariableCollection
{
	GENERATED_BODY()

public:
	/** The collection identifier this class binds under. */
	static constexpr const TCHAR* Collection = TEXT("state");

	virtual FString GetCollectionIdentifier() const override { return Collection; }

	/** Var.state.anything */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tarinoi|Var.state")
	FTarinoiValue Anything;

	/** Var.state.gold */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tarinoi|Var.state")
	double Gold = 12.5;

	/** Var.state.met_ferryman */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tarinoi|Var.state")
	bool MetFerryman = true;

	/** Var.state.mood */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tarinoi|Var.state")
	FString Mood;

	/** Var.state.player_name */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tarinoi|Var.state")
	FString PlayerName = TEXT("Ad\u00e4 \"the\" Bold");

	virtual FTarinoiValue GetVariable_Implementation(FName Name) override;
	virtual void SetVariable_Implementation(FName Name, const FTarinoiValue& Value) override;
};
