// Generated by Tarinoi from the synced content of project 'fixture'.
// Do not edit: regenerating overwrites this file. Implement your bindings in a class
// derived from these, in C++ or in Blueprint.

#pragma once

#include "Bindings/TarinoiBindings.h"
#include "CoreMinimal.h"

#include "TarinoiGeneratedFunctions.generated.h"

/**
 * Functions the author calls as Fn.global.*
 *
 * Derive from this, in C++ or Blueprint, and implement the ones your game uses; bind
 * an instance under "global".
 */
UCLASS(Abstract, Blueprintable, meta = (TarinoiCollection = "global"))
class TARINOITESTS_API UTarinoiFixtureGlobalFunctions : public UTarinoiFunctionCollection
{
	GENERATED_BODY()

public:
	/**
	 * CheckGate(door) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.global")
	bool CheckGate(const FTarinoiValue& Door);

	/** Describe(thing) -> object */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.global")
	FTarinoiValue Describe(const FTarinoiValue& Thing);

	/** PickPin() -> string */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.global")
	FString PickPin();

	/**
	 * Rename(who) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.global")
	void FnRename(const FTarinoiValue& Who);

	/**
	 * Roll(sides, bonus) -> number
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.global")
	double Roll(const FTarinoiValue& Sides, const FTarinoiValue& Bonus);

	virtual bool HasFunction(FName Name) const override;
	virtual bool TryInvoke(FName Name, const TArray<FTarinoiValue>& Args, FTarinoiValue& OutResult) override;
};

/**
 * Functions the author calls as Fn.tarinoi.*
 *
 * Derive from this, in C++ or Blueprint, and implement the ones your game uses; bind
 * an instance under "tarinoi".
 */
UCLASS(Abstract, Blueprintable, meta = (TarinoiCollection = "tarinoi"))
class TARINOITESTS_API UTarinoiFixtureTarinoiFunctions : public UTarinoiFunctionCollection
{
	GENERATED_BODY()

public:
	/**
	 * ClearFlag(flagRef) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void ClearFlag(const FTarinoiValue& FlagRef);

	/**
	 * FlagIsSet(flagRef) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool FlagIsSet(const FTarinoiValue& FlagRef);

	/**
	 * IncrementCounter(counterRef, delta) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void IncrementCounter(const FTarinoiValue& CounterRef, const FTarinoiValue& Delta);

	/**
	 * NumberAtLeast(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool NumberAtLeast(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * NumberAtMost(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool NumberAtMost(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * NumberEquals(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool NumberEquals(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * NumberGreaterThan(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool NumberGreaterThan(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * NumberLessThan(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool NumberLessThan(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * SetCounter(counterRef, value) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void SetCounter(const FTarinoiValue& CounterRef, const FTarinoiValue& Value);

	/**
	 * SetFlag(flagRef) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void SetFlag(const FTarinoiValue& FlagRef);

	/**
	 * SetText(textRef, value) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void SetText(const FTarinoiValue& TextRef, const FTarinoiValue& Value);

	/**
	 * StringEquals(a, b) -> boolean
	 * Effect: pure
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	bool StringEquals(const FTarinoiValue& A, const FTarinoiValue& B);

	/**
	 * ToggleFlag(flagRef) -> void
	 * Effect: mutation
	 */
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "Tarinoi|Fn.tarinoi")
	void ToggleFlag(const FTarinoiValue& FlagRef);

	virtual bool HasFunction(FName Name) const override;
	virtual bool TryInvoke(FName Name, const TArray<FTarinoiValue>& Args, FTarinoiValue& OutResult) override;
};
